-- DROP USER IF EXISTS forum;
CREATE USER forum WITH
    LOGIN
    SUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD 'forum';

-- DROP DATABASE IF EXISTS forum;
CREATE DATABASE forum
    WITH
    OWNER = forum
    TEMPLATE = template0
    ENCODING = 'UTF8'
    -- LC_COLLATE = 'ru_RU.UTF-8'
    -- LC_CTYPE = 'ru_RU.UTF-8'
    CONNECTION LIMIT = -1;